export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
export const LOGGED_OUT_SUCCESS = "LOGGED_OUT_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const MARK_AUTH_TRUE = "MARK_AUTH_TRUE";